### ISSUE TITLE
Why this errors

### ISSUE THREAD

**Issue by Ullash58** [adi1090x/termux-desktop#10]
I can't able to access everything see the screenshot 
Some difference between your screenshot and my  i install step by step
Unable to access some thing whic i provid you [
![Screenshot_2020-04-22-05-08-34-693_com realvnc viewer android](https://user-images.githubusercontent.com/36575445/79935861-98ed1080-8473-11ea-848c-47b987abbb8d.jpg)
![Screenshot_2020-04-22-05-08-40-227_com realvnc viewer android](https://user-images.githubusercontent.com/36575445/79936007-eec1b880-8473-11ea-8026-32cb528d0c7a.jpg)

![IMG_20200422_082354](https://user-images.githubusercontent.com/36575445/79936113-334d5400-8474-11ea-8c21-0e31d1088f39.jpg)
![IMG_20200422_082458](https://user-images.githubusercontent.com/36575445/79936122-36484480-8474-11ea-9161-1fe25feceddf.jpg)

](url)

**Comment by adi1090x** [comment]
edit the scripts according to your device. already mentioned it at the bottom of the page.

**Comment by Ullash58** [comment]
If you are going to install smae things in your termux then you will get errors  so how you will fix it  please provid your your process in which you fix all your problems and if we will get that problem then we will see that so try to understand and re install this in your devices with the help of README.md
