### ISSUE TITLE
can vs code installed?

### ISSUE THREAD

**Issue by DerGoogler** [adi1090x/termux-desktop#101]

**Comment by ZalgoNoise** [comment]
This is not a repo-specific query.

You can install VS Code via `npm`, as its server package (basically running as a web app, not a standalone application). You can configure the exposed port and access password in a config file.

```
npm install -g code-server
```

After running `code-server` you can either reach it within your Android's browser (on http://localhost:{port}) or remotely. It can also be installed as a PWA making it feel actually native. Note that the storage is restricted to where you're installing this package (or, within Termux only).

[NPM package reference - `code-server`](https://www.npmjs.com/package/code-server)
