### ISSUE TITLE
How much storage space needed ??

### ISSUE THREAD

**Issue by AKPR2007** [adi1090x/termux-desktop#105]
Hey, I really like this project and want to install this on my device. But how much storage space is needed?
My device spec:
Ram: 3gb
Storage: 32gb (6.5gb free)
CPU: Snapdragon 632

Please let me know

**Comment by ZalgoNoise** [comment]
Hi,

In my Docker container (installing the same repo) it sums up to 1.6GB total. So, give or take a few MB, I'd recommend reserving about 2GB in your internal storage for this.

As a side note, this repo has been stale for over a year, I am preparing a new project to allow users do install different Desktop Environments. With XFCE for example, it ends up taking about half the storage.

I will try to update all issues once it's done.

**Comment by AKPR2007** [comment]
Wait docker container ?!?!

**Comment by Faris0520** [comment]
Docker ???

**Comment by ZalgoNoise** [comment]
Yes, (for your pc, not your phone) that can be used to test the installation (and desktop access).

See PR #104

**Comment by ezbluntz** [comment]
Check out my all in one Termux/Ubuntu 20.04 Frankenstein commit. Lightwight only 1.6gb after installation 

Consists of a native termux DE with everything working (sound, internet etc) plus rooted ubuntu 20.04 server. 

# NO ROOT NEEDED!!   

https://github.com/ezbluntz/Terbuntu-Frankenstein-Desktop

![Screenshot_20220218-233459](https://user-images.githubusercontent.com/79003657/154811521-241e1912-142a-4dd3-9847-a2c1f13cfd85.png)

![Screenshot_20220218-233539](https://user-images.githubusercontent.com/79003657/154811532-b9b25114-396f-43a7-bb37-429b7cd00c88.png)
 
![Screenshot_20220218-234654](https://user-images.githubusercontent.com/79003657/154811548-fe0d94b0-484b-4163-99e9-1dcc54d46383.png)

![Screenshot_20220218-234859](https://user-images.githubusercontent.com/79003657/154811562-4942b772-8c51-41a4-9e12-724587db6e4b.png)

# Super easy installation!!! 
# No bugs!!!
# Enjoy

**Comment by ezbluntz** [comment]
If you prefer Debian Bullseye, check TerBian Frankenstein

https://github.com/ezbluntz/Terbian-Frankenstein-DE

![Screenshot_20220220-004304](https://user-images.githubusercontent.com/79003657/154821581-d7d9abe5-39d4-45b5-ab34-c056ed067cbe.png)

![Screenshot_20220220-004345](https://user-images.githubusercontent.com/79003657/154821591-04361b11-a287-4a53-b187-8c2374050d31.png)

![Screenshot_20220220-004358](https://user-images.githubusercontent.com/79003657/154821605-b7f5e60f-f574-480b-b190-86cc5fc4c792.png)

![Screenshot_20220220-004410](https://user-images.githubusercontent.com/79003657/154821620-3495025a-d75a-4f04-b01e-6ec13dddbde0.png)

![Screenshot_20220220-004427](https://user-images.githubusercontent.com/79003657/154821629-d6d753cf-271c-4d0c-a330-9c9b47769f05.png)
