### ISSUE TITLE
Unable to open apps due to missing `/etc/machine-id`

### ISSUE THREAD

**Issue by oliver-leung** [adi1090x/termux-desktop#109]
I recently installed Termux Desktop and the VNC server seems to be running pretty smoothly overall, but I'm unable to open some apps. For example, I tried opening the settings manager through the GUI, but nothing would happen. I then tried running `xfce4-settings-manager` in the terminal, which causes the following error:

```
Failed to connect to Xfconf daemon: Cannot spawn a message bus without a machine-id: Unable to load /data/data/com.termux/files/usr/var/data/data/com.termux/files/usr/lib/dbus/machine-id or /data/data/com.termux/files/usr/etc/machine-id: Failed to open file /data/data/com.termux/files/usr/var/data/data/com.termux/files/usr/lib/dbus/machine-id: No such file or directory
```

I found that `/etc/machine-id` is usually generated when Linux is installed, and that it can be regenerated with the command `systemd-machine-id-setup`, but I don't think systemd is meant to be installed on Android/Termux. 

I'm running on a Samsung A52s with Android 11 - let me know if you need any more information about my system.

**Comment by oliver-leung** [comment]
Just managed to fix it! We can use the `dbus-uuidgen` command as follows:

```bash
dbus-uuidgen --ensure=/data/data/com.termux/files/usr/etc/machine-id
```

This generates the machine-id and puts it in the right spot.

**Comment by ZalgoNoise** [comment]
Thanks for sharing the fix @oliver-leung , great troubleshooting 😁

I will review the issue later and file a PR to do necessary checks in order to avoid this.

I will also include it in [my repo](https://github.com/zalgonoise/tdesktop), since I think this repo has been a bit _dormant_ for the past year.

**Comment by ZalgoNoise** [comment]
Hi @oliver-leung ,

I just spent a few mins on this topic and it seems that `/etc/machine-id` is not defined by default with a Termux installation.

I will file a PR today to first find this file and to create it if it doesn't exist.

Thanks again!

**Comment by ZalgoNoise** [comment]
The PR is now submitted in #111. I opened a new issue based off of your report in #110, so that it serves as a placeholder for an open issue while the PR is not yet pushed.

Thank you again!
