### ISSUE TITLE
Openbox

### ISSUE THREAD

**Issue by Ullash58** [adi1090x/termux-desktop#11]
See this error and give solution
![Screenshot_2020-04-23-11-40-16-987_org videolan vlc](https://user-images.githubusercontent.com/36575445/80227175-ed0e1580-866a-11ea-8916-72ba1e2896e7.jpg)
![Screenshot_2020-04-23-11-38-56-822_org videolan vlc](https://user-images.githubusercontent.com/36575445/80227276-09aa4d80-866b-11ea-87d4-73c4fa45bd4f.jpg)
![Screenshot_2020-04-23-11-37-53-122_org videolan vlc](https://user-images.githubusercontent.com/36575445/80227301-12028880-866b-11ea-902c-052bee2e7f11.jpg)
![Screenshot_2020-04-23-11-36-48-318_org videolan vlc](https://user-images.githubusercontent.com/36575445/80227327-1af35a00-866b-11ea-8694-7e4b2a0bd8c9.jpg)
![Screenshot_2020-04-23-11-33-21-362_org videolan vlc](https://user-images.githubusercontent.com/36575445/80227349-1fb80e00-866b-11ea-8c43-9c512cb4fd96.jpg)

**Comment by kikigwin7** [comment]
Same

**Comment by kikigwin7** [comment]
How to fix this? I want use :(

**Comment by adi1090x** [comment]
add this to your shell's config file.
`export PATH=$HOME/Binaries:/usr/local/bin:$PATH`

**Comment by kikigwin7** [comment]
> add this to your shell's config file.
> `export PATH=$HOME/Binaries:/usr/local/bin:$PATH`

Tq works, now i can use this terminal on gui

**Comment by elig0n** [comment]
IMO This should be specified in the README
