### ISSUE TITLE
Unable to open `xfce4-settings-manager` due to missing `/etc/machine-id`

### ISSUE THREAD

**Issue by zalgonoise** [adi1090x/termux-desktop#110]
In reference to #109, this issue is a placeholder for the proposed fix for this behavior.

__Original post__ by @oliver-leung:

> I recently installed Termux Desktop and the VNC server seems to be running pretty smoothly overall, but I'm unable to open some apps. For example, I tried opening the settings manager through the GUI, but nothing would happen. I then tried running `xfce4-settings-manager` in the terminal, which causes the following error:
> 
> ```
> Failed to connect to Xfconf daemon: Cannot spawn a message bus without a machine-id: Unable to load /data/data/com.termux/files/usr/var/data/data/com.termux/files/usr/lib/dbus/machine-id or /data/data/com.termux/files/usr/etc/machine-id: Failed to open file /data/data/com.termux/files/usr/var/data/data/com.termux/files/usr/lib/dbus/machine-id: No such file or directory
> ```
> 
> I found that `/etc/machine-id` is usually generated when Linux is installed, and that it can be regenerated with the command `systemd-machine-id-setup`, but I don't think systemd is meant to be installed on Android/Termux.
> 
> I'm running on a Samsung A52s with Android 11 - let me know if you need any more information about my system.

_Originally posted by @oliver-leung in https://github.com/adi1090x/termux-desktop/issues/109#issue-1104941253_

__Fix__ by @oliver-leung:

> Just managed to fix it! We can use the `dbus-uuidgen` command as follows:
> 
> ```bash
> dbus-uuidgen --ensure=/data/data/com.termux/files/usr/etc/machine-id
> ```
> 
> This generates the machine-id and puts it in the right spot.
> 

_Originally posted by @oliver-leung in https://github.com/adi1090x/termux-desktop/issues/109#issuecomment-1013804729_

**Comment by ZalgoNoise** [comment]
@adi1090x

**Comment by ezbluntz** [comment]
Check out my all in one Termux/Ubuntu 20.04 Frankenstein commit. 

Consists of a native termux DE with everything working (sound, internet etc) plus rooted ubuntu 20.04 server. 

# NO ROOT NEEDED!!   

https://github.com/ezbluntz/Terbuntu-Frankenstein-Desktop

![Screenshot_20220218-233459](https://user-images.githubusercontent.com/79003657/154811521-241e1912-142a-4dd3-9847-a2c1f13cfd85.png)

![Screenshot_20220218-233539](https://user-images.githubusercontent.com/79003657/154811532-b9b25114-396f-43a7-bb37-429b7cd00c88.png)
 
![Screenshot_20220218-234654](https://user-images.githubusercontent.com/79003657/154811548-fe0d94b0-484b-4163-99e9-1dcc54d46383.png)

![Screenshot_20220218-234859](https://user-images.githubusercontent.com/79003657/154811562-4942b772-8c51-41a4-9e12-724587db6e4b.png)

Super easy installation!!!
