### ISSUE TITLE
how to install firefox in this termux gui

### ISSUE THREAD

**Issue by ghost** [adi1090x/termux-desktop#116]

**Comment by Aridlvory** [comment]
**TRY THIS**
`pkg I proot-distro
proot-distro install ubuntu
proot-distro login ubuntu
apt install firefox
export DISPLAY=:1
firefox`

50% probability to work

**Comment by ZalgoNoise** [comment]
@Aridlvory although your input is very appreciated, please note that this solution (and question) are out-of-scope for this issue provided that Firefox isn't available in Termux repos nor the X11 repo.

**Comment by sepahna** [comment]
I see this error!?
proot-distro login ubuntu
root@localhost:~# apt install firefox
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
E: Unable to locate package firefox
root@localhost:~#

**Comment by aldyansyahcp** [comment]
![Screenshot_20220820-094841_1](https://user-images.githubusercontent.com/43259253/185726240-78803389-f953-470a-a501-04a2c5dc627c.png)
i try to install, then error install from snap install firefox cant running
