### ISSUE TITLE
Connection refused error

### ISSUE THREAD

**Issue by AsvkDasher** [adi1090x/termux-desktop#117]
I've done exactly as said in the documentation got no errors while installing, the server started without any errors. But when i tried connecting to it from my PC it shows this error. 
I used TigerVNC and VNCviewer both to see if the problem is the same, and it is.
Please help!
![image](https://user-images.githubusercontent.com/56037475/154404750-b753cc07-1560-41d0-81b7-8504c1b84317.png)

**Comment by ezbluntz** [comment]
Check out my all in one Termux/Ubuntu 20.04 Frankenstein commit. 

Consists of a native termux DE with everything working (sound, internet etc) plus rooted ubuntu 20.04 server. 

# NO ROOT NEEDED!!   

https://github.com/ezbluntz/Terbuntu-Frankenstein-Desktop

![Screenshot_20220218-233459](https://user-images.githubusercontent.com/79003657/154811521-241e1912-142a-4dd3-9847-a2c1f13cfd85.png)

![Screenshot_20220218-233539](https://user-images.githubusercontent.com/79003657/154811532-b9b25114-396f-43a7-bb37-429b7cd00c88.png)
 
![Screenshot_20220218-234654](https://user-images.githubusercontent.com/79003657/154811548-fe0d94b0-484b-4163-99e9-1dcc54d46383.png)

![Screenshot_20220218-234859](https://user-images.githubusercontent.com/79003657/154811562-4942b772-8c51-41a4-9e12-724587db6e4b.png)

Super easy installation!!!

**Comment by ezbluntz** [comment]
If you prefer Debian Bullseye, check TerBian Frankenstein

https://github.com/ezbluntz/Terbian-Frankenstein-DE

![Screenshot_20220220-004304](https://user-images.githubusercontent.com/79003657/154821581-d7d9abe5-39d4-45b5-ab34-c056ed067cbe.png)

![Screenshot_20220220-004345](https://user-images.githubusercontent.com/79003657/154821591-04361b11-a287-4a53-b187-8c2374050d31.png)

![Screenshot_20220220-004358](https://user-images.githubusercontent.com/79003657/154821605-b7f5e60f-f574-480b-b190-86cc5fc4c792.png)

![Screenshot_20220220-004410](https://user-images.githubusercontent.com/79003657/154821620-3495025a-d75a-4f04-b01e-6ec13dddbde0.png)

![Screenshot_20220220-004427](https://user-images.githubusercontent.com/79003657/154821629-d6d753cf-271c-4d0c-a330-9c9b47769f05.png)
