### ISSUE TITLE
Does it need to install ZSH?

### ISSUE THREAD

**Issue by abraxas86** [adi1090x/termux-desktop#122]
I'm probably an outlier in this one, but does it have to install ZSH?  The package should just install the requirements for the desktop environment and remote server.  I love the the ease of configuring everything with this; but ZSH breaks a lot of other stuff I use due to the custom font pack it needs.

**Comment by Umbragloom** [comment]
You can always edit the install script to not download zsh, and download what ever shell you like, but make sure you also adjust the install script section with zsh or it could error out.
