### ISSUE TITLE
Use a PC to view the VNC screen hosted by phone

### ISSUE THREAD

**Issue by Igao3Mil** [adi1090x/termux-desktop#128]
So, I have a phone that the screen doesn't, and it is pretty useless. I wanted to transform it in kinda of a server, or at least another "PC". But the problem is, even with the TigerVNC, I can't connect to the server, it says: "Unable to connect to socket: Host is down"
Is there any way to just start the server, leave the phone anywhere and use it from the PC?

**Comment by NelsonGuiamba** [comment]
you need to connect your mobile to your PC using hostpot or bluetooth share internet, check what  is your ip address on your pc then create a vnc conection with your ip:5901

**Comment by Dispnser** [comment]
you need to start vnc server and connect to it with "your ip here":1
