### ISSUE TITLE
Polybar battery section shows no percentage digits

### ISSUE THREAD

**Issue by elig0n** [adi1090x/termux-desktop#13]
**The Problem**: Polybar's `battery` section only shows '%' without a number.

![scrcpy_iAvaEZDi1w](https://user-images.githubusercontent.com/31196036/83352229-cbcbd380-a352-11ea-9f74-78c7a4101356.png)

Checking the provided `battery` script I have found that it tries to receive information from `/sys/class/power_supply/battery` but I received Permission Denied when trying to access directory `/sys/class/power_supply/battery` or its content via `cat` and `cd` in a Termux terminal. I could only cd up to `/sys/class/power_supply`.

My device is not rooted.

**Comment by adi1090x** [comment]
@elig0n Repository Updated, Please try again.
