### ISSUE TITLE
Error installing desktop-file-utils, Terminating...

### ISSUE THREAD

**Issue by hotcatto73** [adi1090x/termux-desktop#130]
![Screenshot_2022-05-31-01-36-00-122_com termux](https://user-images.githubusercontent.com/103116023/171054141-349b322a-96d9-4573-92f1-eac27eb493b2.jpg)

**Comment by blueOkiris** [comment]
I have also hit this issue

**Comment by DevonGi** [comment]
Install termux Api

**Comment by blueOkiris** [comment]
That worked for me. I feel so dumb for over looking that in the README. Hopefully it works for the other guy as well
