### ISSUE TITLE
Desktop files utility not found

### ISSUE THREAD

**Issue by mrfoxie** [adi1090x/termux-desktop#132]
I tried to install using installer script but it gave me error of 
```
Checking availability of current mirror:
[*] (11) https://termux.librehat.com/apt/termux-main: ok
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
E: Unable to locate package desktop-file-utils

[!] Error installing desktop-file-utils, Terminating...
```
here is the screenshot of it.
![Screenshot_20220615-181929_Termux](https://user-images.githubusercontent.com/25217451/173831368-ef9175d7-9992-4e82-919e-bb290a3d5a96.png)

**Comment by JimmyNeutronBitch** [comment]
do you have termux-api installed?

**Comment by mrfoxie** [comment]
> do you have termux-api installed?

yes

**Comment by CliveKBinu** [comment]
I have the same problem also

**Comment by 2096779623** [comment]
`pkg i x11-repo` first.
