### ISSUE TITLE
black screen

### ISSUE THREAD

**Issue by dexi22** [adi1090x/termux-desktop#134]
![Screenshot_2022-07-27-12-03-18-786_com realvnc viewer android](https://user-images.githubusercontent.com/65784455/181209309-40c8cd1a-f7be-42ff-9b2f-36ee95faff64.jpg)

**Comment by minhdanlc124** [comment]
try chmod u+x ~/.vnc/xstartup

**Comment by 0pLuS0** [comment]
I have a black blank screen too...

**Comment by se7ennnnnn** [comment]
> try chmod u+x ~/.vnc/xstartup

Thx It's helpful
