### ISSUE TITLE
Help I Have An Black When I Try To Vnc To the gui

### ISSUE THREAD

**Issue by Guende** [adi1090x/termux-desktop#135]
![Screenshot_2022-07-27-13-20-47-831_com realvnc viewer android](https://user-images.githubusercontent.com/85771688/181354808-01aa8c94-cafa-4e4a-9703-29178b684472.jpg)

**Comment by rishi2004-sudo** [comment]
I am also encountering same problem stuck in black screen
![Screenshot_2022-08-04-19-12-55-15_8659c1e795b4b4239e38d87c88c077b3](https://user-images.githubusercontent.com/110611297/182862180-25616ac2-66ab-4cdd-8257-bbcd3fb1dd38.jpg)

**Comment by simeonradivoev** [comment]
Same here

**Comment by minhdanlc124** [comment]
try chmod u+x ~/.vnc/xstartup
