### ISSUE TITLE
Help I have a graphic error.

### ISSUE THREAD

**Issue by alanreypato** [adi1090x/termux-desktop#138]
My desktop look like this, and I don't know what I can make, pls help.
![Screenshot_2022-09-10-07-53-52-869_com.realvnc.viewer.android~2.jpg](https://user-images.githubusercontent.com/90100369/189485809-13fcaad1-33d3-4a6d-9272-322ca262d31d.jpg)

**Comment by koji-takahiro** [comment]
> 

In VNC Viewer, set "Image Quality" to High

**Comment by medjakub** [comment]
Thanks! This problem should be mentioned in README.md in installation information.
