### ISSUE TITLE
E: Package 'htop-legacy' has no installation candidate 

### ISSUE THREAD

**Issue by khansaad1275** [adi1090x/termux-desktop#141]
**My Device info:**
OS: Android 13 aarch64
Host: google Pixel 4 XL
Kernel: 4.14.276-ge333cb8619d0-ab8811257

**ERROR:**

> This may mean that the package is missing, has been obsoleted, or
> is only available from another source
> **However the following packages replace it:
>   htop**
> 
> **E: Package 'htop-legacy' has no installation candidate**
> 
> [!] Error installing htop-legacy, Terminating...

This is terminating the installation of the script, maybe we just need to change the htop-legacy to htop? 
this is happening while I am trying to install the script by typing `./setup.sh --install`

**FIX:**
Line 57 in setup.sh : just change 'htop-legacy' to 'htop' and it will work, i am not creating PR because i am not sure if this is only my issue or everyone is getting the same error.

**UPDATE :**
I forked the repo and fixed the issue, so if you want you can just use my repo, till this gets fixed. : https://github.com/khansaad1275/termux-desktop-Bug-Fixed

**Comment by CriticalRange** [comment]
Yeah I'm getting it too
My Device settings in-case it's needed:
OS: Android 9 aarch64 (LineageOS 16 Unofficial build)

**Comment by C4l1b3r** [comment]
Package 'htop-legacy' has no installation candidate

Samsung Galaxy Note20 same issue just started recently

**Comment by CSIR-WStafford** [comment]
Thanks. Editing setup.sh worked for me on Android 11 and solved the failed installation due to 'Package htop-legacy has no installation candidate'
