### ISSUE TITLE
error installing htop-legacy

### ISSUE THREAD

**Issue by lexzee** [adi1090x/termux-desktop#145]
Package htop-legacy is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source
However the following packages replace it:
  htop

E: Package 'htop-legacy' has no installation candidate

**Comment by khansaad1275** [comment]
> Package htop-legacy is not available, but is referred to by another package. This may mean that the package is missing, has been obsoleted, or is only available from another source However the following packages replace it: htop
> 
> E: Package 'htop-legacy' has no installation candidate

https://github.com/adi1090x/termux-desktop/issues/141

This issue is already mentioned here with a solution.

**Comment by lexzee** [comment]
Thank you
