### ISSUE TITLE
I Have A Black/Blank Screen

### ISSUE THREAD

**Issue by 0pLuS0** [adi1090x/termux-desktop#146]
Hello,

I followed all the directions corretly, and when I start, I have nothing but a black blank screen.

I've used Linux for a very long time, my distro is Slackware, I also only have installed in Slack Openbox too, so I'm no stranger to Linux or Openbox.

Something is not working here.

My Specs:
--------------
OnePlus 5T
ROM: /e/ - R Android 11
Rooted: Yes - Magisk
VNC Viewer: 3.7.1.44443

```Here's termux-log```

[termux-log.txt](https://github.com/adi1090x/termux-desktop/files/9874593/termux-log.txt)

```Here's localhost:1.log from .vnc```

[localhost:1.log.txt](https://github.com/adi1090x/termux-desktop/files/9874635/localhost.1.log.txt)

```Blank screen```

![TermuxDesktop](https://user-images.githubusercontent.com/36190223/198161582-9bffe48b-e9e3-4601-a304-53c4cd4ec28f.jpg)

When I restart termux and open it back up and type startdesktop, it always says the server is already running, and asks if I want to kill it.

If I type Y to kill it, it comes back saying bad system call at line 19.

```At the linux prompt, ran startdesktop, shows server already running and when trying to kill bad call.```

![startdesktop](https://user-images.githubusercontent.com/36190223/198167021-d235ae6e-7f25-4a90-aa86-56a4d7b9dc10.jpg)

Looks like the server keeps running in the background after closing everything down, Linux and Termux.

**Comment by 0pLuS0** [comment]
Rebooting my phone solved the issue.

It appears there's a problem, when first completing the install of Termux Desktop, and tryping startdesktop for the first time, the VNC server as I mentioned is already running, which I'm assuming shouldn't be.

I tried to kill it from the cli, but it didn't work.

If there's ever another VNC Server issue, what is the cmd to kill the server at the terminal?

**Comment by Daexxxx** [comment]
Hi I have the same problem as you but I know how to fix it 

So first you need to kill the vnc server with this command:
`vncserver -kill :1`
Then you start it again with:
`vncserver`

I hope this helps you 

David

**Comment by Kabirlatif** [comment]
Just pkg install aterm xorg-twm

**Comment by aternolinux** [comment]
> Just pkg install aterm xorg-twm

Aterm just makes a terminal we a want a gui a full one
