### ISSUE TITLE
Package 'htop-legacy' has no installation candidate  [!] Error installing htop-legacy, Terminating...

### ISSUE THREAD

**Issue by Vintnobu** [adi1090x/termux-desktop#157]
Package 'htop-legacy' has no installation candidate

[!] Error installing htop-legacy, Terminating...

**Comment by TheRedM** [comment]
In ```setup.sh``` line 57 change ```htop-legacy``` to ```htop``` and save, run ```.\setup.sh --install``` again, that should fix the issue, not sure what's the difference between ```htop-legacy``` and ```htop``` I hope the dev can fix it, because of there is major difference between ```htop-legacy``` and ```htop``` that can cause issues.

**Comment by mgmtlife10** [comment]
> In `setup.sh` line 57 change `htop-legacy` to `htop` and save, run `.\setup.sh --install` again, that should fix the issue, not sure what's the difference between `htop-legacy` and `htop` I hope the dev can fix it, because if there are major difference between `htop-legacy` and `htop` that can cause issues.

How do I edit it?

**Comment by Basijd** [comment]
> 

How to change line no. 57
I,m new here please
