### ISSUE TITLE
httop-legacy...

### ISSUE THREAD

**Issue by finnroth09** [adi1090x/termux-desktop#162]
![Screenshot_20221207-160750](https://user-images.githubusercontent.com/98442142/206307234-1dfc73fb-2b09-4986-8509-e1f5f619e366.png)

**Comment by dimlux-dev** [comment]
same problem((

**Comment by RHXOXOME** [comment]
Yes. Thats the problem. There's no 'htop-legacy' packages on Termux repo.

**Comment by mrfoxie** [comment]
i have successfully solved it just edit setup.sh and find htop-legacy and replace it with htop

**Comment by DosAEG** [comment]
How to edit setup.sh

**Comment by mrfoxie** [comment]
> How to edit setup.sh

use `nano` editor to edit the file

**Comment by PegHorse** [comment]
I confirm it's working by editing the setup.sh :)

**Comment by ersin3381** [comment]
I have fixed version in my profile you can use it is.
