### ISSUE TITLE
Htop-legacy is gone

### ISSUE THREAD

**Issue by glowingstone124** [adi1090x/termux-desktop#171]
I want install this desktop on my termux app, but i can't install htop-legacy, it's replaced by htop.
Can you fix this?

**Comment by Dragon740f** [comment]
![Screenshot_2023-03-07-16-43-38-741_com.termux.jpg](https://user-images.githubusercontent.com/80297629/223369816-361016d5-73bf-4df9-8e9c-bf35263cce7e.jpg)

Fix this bug by edit the setup.sh.

**Comment by taeable** [comment]
Thank you, that fixed the issue for me as well.
Replace "htop-legacy" with "htop" in line 56 and that should fix the setup script.

**Comment by VISHAWANATH953** [comment]
why not we change git repo

**Comment by adi1090x** [comment]
Fixed.
