### ISSUE TITLE
Can't install ,htop-legacy issue

### ISSUE THREAD

**Issue by rexackermann** [adi1090x/termux-desktop#175]
```
Checking availability of current mirror:
[*] https://mirror.albony.xyz/termux/termux-main: ok
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Package htop-legacy is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source
However the following packages replace it:
  htop

E: Package 'htop-legacy' has no installation candidate

[!] Error installing htop-legacy, Terminating...
```

Possible fix

replace htop-legacy with htop

**Comment by BestInfinity** [comment]
had the same issue, just use nano to edit the install file and change htop-legacy into htop

**Comment by Basijd** [comment]
> had the same issue, just use nano to edit the install file and change htop-legacy into htop

How please step by step guide

**Comment by BestInfinity** [comment]
I don't really recall how it is setup but iirc it's just a sh file so just do nano /directory/to/sh/file/shfile then find where it says htop-legacy and remove the -legacy yk delete

**Comment by adi1090x** [comment]
Fixed.
