### ISSUE TITLE
Is it possible to add additional repositories? or use pacman -Sy command in a way that works

### ISSUE THREAD

**Issue by Yamada6612** [adi1090x/termux-desktop#176]
The termux repository has very few programs, I wanted to be able to extend this catalog with additional repositories, or even install Pamac or any other store to make it easier to use

**Comment by Yamada6612** [comment]
The termux repository has very few programs, I wanted to be able to extend this catalog with additional repositories, or even install Panaca or any other store to make it easier to use

**Comment by Yamada6612** [comment]
A

**Comment by adi1090x** [comment]
It's not Arch.
