### ISSUE TITLE
How to add Applications on Desktop ?

### ISSUE THREAD

**Issue by SUMITDEY69** [adi1090x/termux-desktop#178]
How to add Applications on Desktop?

See the image
![Screenshot_2023-05-29-00-23-01-21_8659c1e795b4b4239e38d87c88c077b3](https://github.com/adi1090x/termux-desktop/assets/108204481/493e6cb1-4607-4194-b8c8-e82ce209784a)

**Comment by SUMITDEY69** [comment]
I want to add Applications on the home page of the desktop

**Comment by AdrianoTisera** [comment]
Openbox is a Window manager, so it isn't responsible for desktop icons. You can try and use Nautilus, PCManFM or Spacefm, but I couldn't find these programs in the repositories. You could try to install xfdesktop which also manages desktop icons and depends on Thunar, which should be already installed.
