### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Keller18306** [adi1090x/termux-desktop#18]
when i connect i see it
![Screenshot_2020-08-24-02-19-23-901_com realvnc viewer android](https://user-images.githubusercontent.com/23178771/90991282-8cf39580-e5b0-11ea-9d9e-c8d38122cb0f.png)

**Comment by LunatikReal** [comment]
Me too, but also the console and the screen refreshes for a short time if I switch to Termux and back to VNC.
![Screenshot_20201028_012215](https://user-images.githubusercontent.com/11047616/97357813-2fcfd500-18bc-11eb-93b4-dc1ca1bf2430.jpg)

**Comment by Zaimy027dec** [comment]
Same issue

**Comment by LunatikReal** [comment]
Here's what to do:
1) pkg install xfce4
2) in (~/.vnc/xstartup) insert "xfce4-session &"

**Comment by Zaimy027dec** [comment]
Bro plz... talk to me on Instagram my insta.. account is @its_zaimy_27
you've already my unread msg

Plz... Help me

**Comment by adi1090x** [comment]
@LunatikReal @Keller18306
Sorry for delays, Been very busy on other stuff.
BTW, Repository Updated,... Please try again.
