### ISSUE TITLE
browser not found

### ISSUE THREAD

**Issue by Keller18306** [adi1090x/termux-desktop#23]
browser not found
![Screenshot_2020-11-08-23-29-43-134_com realvnc viewer android](https://user-images.githubusercontent.com/23178771/98483570-89b88f00-221a-11eb-833f-8cbf46b098dd.png)

**Comment by Keller18306** [comment]
also when I run xarchiver nothing happens

**Comment by Keller18306** [comment]
many settings go to perpetual loading
![Screenshot_2020-11-08-23-38-17-235_com realvnc viewer android](https://user-images.githubusercontent.com/23178771/98483704-a43f3800-221b-11eb-86c7-788cc2e18c8d.png)

**Comment by adi1090x** [comment]
add netsurf-gtk3 in that dialog

**Comment by Paresh-Maheshwari** [comment]
I don't know how to install browser in  this destop

**Comment by Paresh-Maheshwari** [comment]
Please tell me ho can i do this

**Comment by Yisus7u7** [comment]
Es censillo, pero solo admite 1 navegador, por lo que tengo entendido, abre la termina y pon : 

pkg install netsurf 

y luego cuando ejecutes el navegador, abre el explorador de archivos y en buscar buscas un archivo llamado netsurf-gtk3 y lo seleccionas, y listo

**Comment by Paresh-Maheshwari** [comment]
I am unable to find netsurf-gtk3 file in termux
can you tell me whare file is created

**Comment by Aaron75A** [comment]
Se podrá instalar Chrome o uno como Firefox?

**Comment by Paresh-Maheshwari** [comment]
> Se podrá instalar Chrome o uno como Firefox?

No

**Comment by Yisus7u7** [comment]
> ¿Se podrá instalar Chrome o uno como Firefox?

No, sólo netsurf o w3w
