### ISSUE TITLE
Getting plain black screen 

### ISSUE THREAD

**Issue by mishraanuj205** [adi1090x/termux-desktop#28]
![Screenshot_2020-11-13-23-22-15-06](https://user-images.githubusercontent.com/44110170/99104577-2b6b2200-2607-11eb-80f6-b9aec13e2839.png)
Getting this weird black screen with cursor I have done all the setup correctly for 5th time now but no luck I have tried vnc viewer and X server XSDL please help me

**Comment by sempai-kz** [comment]
Do you want a remote GUI?

**Comment by ZalgoNoise** [comment]
Update with relevant information please:
- Device and android version
- Steps taken (since you launch Termux) 
- Termux output when you run the vnc server?
- any logs under the `~/.vnc` folder

**Comment by mishraanuj205** [comment]
Packages CPU architecture:
aarch64
Subscribed repositories:
# sources.list
deb https://main.termux-mirror.ml/ stable main
# game-repo (sources.list.d/game.list)
deb https://dl.bintray.com/grimler/game-packages-24 games stable
# science-repo (sources.list.d/science.list)
deb https://dl.bintray.com/grimler/science-packages-24 science stable
# unstable-repo (sources.list.d/unstable.list)
deb https://dl.bintray.com/xeffyr/unstable-packages unstable main
Updatable packages:
All packages up to date
Android version:
8.1.0
Kernel build information:
Linux localhost 4.9.82-perf+ #2 SMP PREEMPT Tue Oct 20 12:12:25 CST 2020 aarch64 Android
Device manufacturer:
OPPO
Device model:
CPH1809

I have followed this steps here on termux wiki https://wiki.termux.com/wiki/Graphical_Environment

Just plain black screen with a cursor

Currently I lost hope so I removed VNC and all the cache related to VNC/TigerVNC so no logs their

**Comment by mishraanuj205** [comment]
> Do you want a remote GUI?

Yeah Dude

**Comment by elig0n** [comment]
I had the same problem. Make sure. vnc/xstartup has executable permission set. i. e. `chmod u+x ~/.vnc/xstartup` and try again.

**Comment by Hiimsuchnooblmao** [comment]
Hi guys, im i just started using termux and i got the same problem, can you give me a step by step solution? Please make it as simple as possible since im noob and i wouldn't understand any hard programming language

**Comment by devincrack** [comment]
I have the same problem , But when i install this pip package , boom all is done

The package is
"pip install pyxdg"

**Comment by ZalgoNoise** [comment]
Hi all,

Thanks for all your input, happy to see the ball rolling for many who were facing this issue.

I think PR #102 and #103 should resolve the issue where the startup script isn't found, which should be launching `vncserver` (as already pointed out by @ezbluntz and @wonder992).

I will look into `pyxdg` ASAP and open a new PR to check for it and install it if needed, and also adding it to my repo at [ZalgoNoise/tdesktop](https://github.com/ZalgoNoise/tdesktop)

**Comment by beastzx18** [comment]
i am getting this same error, i solved this error somehow a long time ago but i don't remember now

**Comment by hakxcore** [comment]
Someone found solution please give some stepwise Sol.

**Comment by Saikatsaha1996** [comment]
> Someone found solution please give some stepwise Sol.

With android 13 have this issue..

I also have same issue.. 
This is not termux-x11 or vnc issue..
Debian destro will work fine..

**Comment by Rohit07000** [comment]
> ![Screenshot_2020-11-13-23-22-15-06](https://user-images.githubusercontent.com/44110170/99104577-2b6b2200-2607-11eb-80f6-b9aec13e2839.png) Getting this weird black screen with cursor I have done all the setup correctly for 5th time now but no luck I have tried vnc viewer and X server XSDL please help me

How to solv this problem

**Comment by Rohit07000** [comment]
How to solv this problem
