### ISSUE TITLE
Failed to apply theme & Taskbar hanging after some time

### ISSUE THREAD

**Issue by superuser789** [adi1090x/termux-desktop#29]
I installed termux-desktop following steps as mentioned in the github page. It installed successfully and all things were working well for the first time.
Then I changed themes using `Preferences->ChangeStyle` , Taskbar was gone and theme was not applied , only wallpaper was changed when I changed to a different theme. I restarted vnc server to check again. But did not work. Then  I reinstalled using `./setup.sh --uninstall ; ./setup.sh --install` . But still not working.
Using htop , I saw, all the desktop programs were running, So I killed them using  `pkill -9 -u `id -u termuxUserID``.
After starting vnc server again, Theme was applied and taskbar was running but taskbar hangs after some time.

**Comment by superuser789** [comment]
Problem solved. I had not installed [termux-api](https://play.google.com/store/apps/details?id=com.termux.api&hl=en) app from play store. After installation , desktop worked fine.
Thanks.

**Comment by Atharv-Pathak-14** [comment]
Where is preferences I can't see it
