### ISSUE TITLE
how to setup tigervnc so XKV extension will be available to window manager

### ISSUE THREAD

**Issue by JanuszChmiel** [adi1090x/termux-desktop#3]
This question is not only relate d for Termux. But because I do not see at all and because I want to replace Xserver XSDL by some VNC server and VNC client app for Android. I would like to know, if there is An way to setup VNC server and find VNC client Android app, which will support XKB extension and which will support hardware Bluetooth or USB keyboard so keys and keyboard shortcuts will be also detected by running X app. Do you know about some technique?
Or this approach work only with full linux wich run XORG and some Xorg extension for other VNC server must be installed?
Or nobody have developed VNC server which support XKB extension for running window manager?
Thank you very very much for yours answer. It seems to Me, that you are truly professional so I hope, that you will give Me some advice.
Thank you very much for yours answer.
Satisfied visually impaired user of Android, Termux and Proot technology, which allows Me to even run Debian with Orca screen reader thanks to Pulseaudio for Termux, even Espeak and Speech-dispatcher can work.

**Comment by adi1090x** [comment]
No idea, never tried. But it should work on vnc viewer for Android.
