### ISSUE TITLE
Music player button icon not showing properly.

### ISSUE THREAD

**Issue by Zack0ne** [adi1090x/termux-desktop#33]
![bug-report3](https://user-images.githubusercontent.com/62429947/100360185-910dd400-3033-11eb-9a26-fe868fd35f6e.png)

I've tried changing font and restarting.
this include battery status, network info and exit menu.

works fine just the appearance

**Comment by Ankit3k** [comment]
In my case, when I clicked the stop button on this music player it got dissapeared and I am unable to get it back .
How can I get it back???? 
Help me !!,.

**Comment by Zack0ne** [comment]
> In my case, when I clicked the stop button on this music player it got dissapeared and I am unable to get it back .
> How can I get it back????
> Help me !!,.

Stop means closing the music player, you can get it back by starting the music player again by running `ncmpcpp` thru terminal or menu.

Tell me if i wrong.

**Comment by Ankit3k** [comment]
Yeah Great!! Thanks man

**Comment by Ankit3k** [comment]
> > In my case, when I clicked the stop button on this music player it got dissapeared and I am unable to get it back .
> > How can I get it back????
> > Help me !!,.
> 
> Stop means closing the music player, you can get it back by starting the music player again by running `ncmpcpp` thru terminal or menu.
> 
> Tell me if i wrong.

Thanks..
It's working

**Comment by khansaad1275** [comment]
> ![bug-report3](https://user-images.githubusercontent.com/62429947/100360185-910dd400-3033-11eb-9a26-fe868fd35f6e.png)
> 
> I've tried changing font and restarting. this include battery status, network info and exit menu.
> 
> works fine just the appearance

Where is music player? because i don't even see an option for a gui based music play. please help.

**Comment by Zack0ne** [comment]
> 

it's been 2 year. uninstalled everything, i know nothing now, sorry

**Comment by khansaad1275** [comment]
> > 
> 
> it's been 2 year. uninstalled everything, i know nothing now, sorry

lol okay <3
If someone else is reading this please help me.
