### ISSUE TITLE
dock and taskbar?

### ISSUE THREAD

**Issue by americanitunes101** [adi1090x/termux-desktop#4]
Followed instructions by the letter but I have no application dock or top task bar. 
I need to right click to open terminal, and when I do I get the error 

> OPENBOX failed to execute child process "sterm" (no such file or directory)

**Comment by adi1090x** [comment]
Try doing it again on a freah termux installation.
The error above shows, sterm isn't installed in termux.

**Comment by Sandjarka** [comment]
Hi there. I've tried to reinstall everything for like 3 times and I still do have the same issue. Is there anyway to solve it? Thx!

P.S. Using Samsung Tab S5e

**Comment by mrevilcorp** [comment]
Yes, the same as what I guarantee you sir, the menu and status bar no blenk only the wallpaper that appears

**Comment by olivmonnier** [comment]
Same issue with my Samsung S10

**Comment by lostallmymoney** [comment]
Same

**Comment by mukhtharcm** [comment]
Mine also errors

**Comment by adi1090x** [comment]
`usr/lib/archlabs/common`, this is **important** for openbox menus.
