### ISSUE TITLE
Package 'dbus' has no installation candidate

### ISSUE THREAD

**Issue by Fevirre** [adi1090x/termux-desktop#45]
So when I go to run ./setup.sh --install it installs just about 1st half of the setup and then after curl is installed the line puts out this output:

[*] Package curl installed successfully.

Checking availability of current mirror: ok
Reading package lists... Done
Building dependency tree
Reading state information... Done
Package dbus is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

E: Package 'dbus' has no installation candidate

There's no way to install the desktop now, hopefully this gets fixed

**Comment by hacker00-ctrl** [comment]
same here

**Comment by Gurren-Joestar** [comment]
O have the same kind of problem but with openssl-tool

**Comment by Gurren-Joestar** [comment]
@Fevirre 

Try to install again, if this dont work try to update your repository and  dowload it by pkg 

`pkg update
pkg upgrade
pkg install dbus`

If that dont work, try to close your termux session and repeat the procedure.

If it still continue dont working, just wait a bit a try again.

I had a similar problem with many packages, and it worked for me

**Comment by phillmugs** [comment]
same for me for openssl-tool

**Comment by phillmugs** [comment]
i solved all errors with pkg upgrade && pkg update  it then finished installing ... on tecno k7 ... Android 7
