### ISSUE TITLE
How to add music ?

### ISSUE THREAD

**Issue by ghost** [adi1090x/termux-desktop#48]
I put an MP3 song in the music folder but it wasn’t anyone know if you need to do anything else?

**Comment by Yisus7u7** [comment]
Copie los archivos de música a la carpeta ~/Music

**Comment by zFASTsrC** [comment]
Thanks to help me

Em qui, 27 de mai de 2021 00:36, Yisus7u7 ***@***.***>
escreveu:

**Comment by Yisus7u7** [comment]
Le recomiendo usar mi proyecto :  
https://github.com/Yisus7u7/termux-desktop-xfce
