### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by yudi-plolong** [adi1090x/termux-desktop#54]
Hello friends,I got this problem.is there someone willing to help me.
![Screenshot_2021-03-29-06-46-02-766_com termux](https://user-images.githubusercontent.com/66744790/112772356-79cf0980-905a-11eb-8f16-77143a1a4399.png)

**Comment by ZalgoNoise** [comment]
```
calc/stable 2.12.8.0 aarch64
  Arbitrary precision console calculator
```

Please run `apt update`, there is a PR for this already.

**Comment by Yisus7u7** [comment]
Some very good alternatives to this project:

https://github.com/Yisus7u7/termux-desktop-xfce

https://github.com/Yisus7u7/termux-desktop-lxqt
