### ISSUE TITLE
Backing Up

### ISSUE THREAD

**Issue by msn-05** [adi1090x/termux-desktop#59]
It takes a ridiculous amount of time to install this. Is there a way to back up this to internal storage?
https://wiki.termux.com/wiki/Backing_up_Termux
Can I use this method 👆?
If yes then how?

**Comment by Aridlvory** [comment]
It's simple

**BACKING UP**

1) give storage permission to termux
`termux-setup-storage`
2) Go to Termux base directory 
(Copy paste this command)
`cd /data/data/com.termux/files`
3) copy paste this command it may take some time
`tar -zcvf /sdcard/termux-backup.tar.gz home usr`


If it is a success u will see a file in your internal storage named _termux.tar.gz_


**RESTORING**

Repeat the first 2 steps of backing up. After that...

3) copy paste this command
`tar -zxf /sdcard/termux-backup.tar.gz --recursive-unlink --preserve-permissions`

# ALERT--DONT MOVE THE _termux.tar.gz_ FILE BEFORE BACKING UP

After the 3rd step u could see that termux is not working wait for a minute and close termux with the exit button in the notification panel

Open it again

HOORAY!! you got all your files in your new termux

ENJOY!! 😁
