### ISSUE TITLE
Readme update - polybar package

### ISSUE THREAD

**Issue by nathaneltitane** [adi1090x/termux-desktop#6]
polybar requires libnl to be installed to function

**Comment by MuhdNurHidayat** [comment]
oh, finally I know why the top bar doesn't appear.. installed libnl and it now appears...

but this on other hand is still not solved so I'm digging deeper:
![Screenshot_20200314-110729_VNC Viewer](https://user-images.githubusercontent.com/12217018/76673848-2cfdc980-65e4-11ea-8aca-63a71faefecc.jpg)

**Comment by mukhtharcm** [comment]
@MuhdNurHidayat  post it here if you get it.. 
thanks in advance.. :)

**Comment by adi1090x** [comment]
check path in `~/.zshrc`
