### ISSUE TITLE
XSDL 

### ISSUE THREAD

**Issue by IgorMiracle** [adi1090x/termux-desktop#60]
Is it possible to run this desktop via XSDL? I tried but it starts up with errors
![S10422-08014905](https://user-images.githubusercontent.com/82994577/115658217-02328880-a341-11eb-8c8f-698357522d1d.jpg)

**Comment by shim80** [comment]
I'm actually using xWayland. I was able to launch the desktop using command "openbox-session", but there's no input and the screen freeze

**Comment by TriMoon** [comment]
The only reason i have not tried this repo is because it needs a vnc-client...
Im also using XSDL and am running xfce4...
