### ISSUE TITLE
Xauth does not exist

### ISSUE THREAD

**Issue by abs0023** [adi1090x/termux-desktop#62]
I've run into this issue:
file /data/data/com.termux/files/home/.Xauthority does not exist
It's probably why I get a black screen in the desktop.
The device is a oneplus 8t with LineageOS 18.1

**Comment by abs0023** [comment]
The device is a one plus 8t

**Comment by abs0023** [comment]
With official LOS 18.1

**Comment by osoiyo** [comment]
I have the same issue, I tried: 
re-install it after `termux-chroot`
after startdesktop, I found an error in ~/.vnc/localhost:1.log
it was : PyXDG is required

I installed it,  `pip install pyxdg`  then restart 
OOOOh it works!

**Comment by dark-horse10** [comment]
> I have the same issue, I tried:
> re-install it after `termux-chroot`
> after startdesktop, I found an error in ~/.vnc/localhost:1.log
> it was : PyXDG is required
> 
> I installed it, `pip install pyxdg` then restart
> OOOOh it works!

Thanks❤...., it works.

**Comment by abs0023** [comment]
Sorry I didn't took time to thank you for your answer.
