### ISSUE TITLE
Web browser doesn't support JavaScript

### ISSUE THREAD

**Issue by qwerty65432** [adi1090x/termux-desktop#64]
The program 'netsurf' doesn't support JavaScript.
Are you know some graphical browsers for termux-desktop? 
Or a way to fix this netsurf program issue?
Help. : ]

**Comment by ezioauditore009** [comment]
no need to use browser then use ur android browser instead

**Comment by qwerty65432** [comment]
> no need to use browser then use ur android browser instead

Are you using Linux deploy?
