### ISSUE TITLE
How to get on screen keyboard + right mouse click ? Also the pointer isn't clicking where my finger is.

### ISSUE THREAD

**Issue by silruin** [adi1090x/termux-desktop#69]
One Plus 7T
Everything else worked like a charm.

Ive been using Archcraft so this is awesome.

**Comment by Yisus7u7** [comment]
Some very good alternatives to this project:

https://github.com/Yisus7u7/termux-desktop-xfce

https://github.com/Yisus7u7/termux-desktop-lxqt
