### ISSUE TITLE
Task bar and dock 

### ISSUE THREAD

**Issue by Kymonlucky** [adi1090x/termux-desktop#7]
How can i fix this? The dock and task bar is not appearing

**Comment by nathaneltitane** [comment]
@Kymonlucky you need to go through the scripts and adjust things according to your device's soecifications

**Comment by Kymonlucky** [comment]
How??

**Comment by nathaneltitane** [comment]
@Kymonlucky by looking into the appropriate directories and modifying the code to fetch whatever it is you need for it to work - if you are not familiar with linux or android and the way it functions, i suggest you look into the basics first.

**Comment by Kymonlucky** [comment]
Where specific directory should I start?

**Comment by adi1090x** [comment]
read the scripts, you'll get the idea. i can't do it. it's different for different devices, that's why i've mentions already to modify scripts according to your device.
