### ISSUE TITLE
How update Termux Desktop without data loss

### ISSUE THREAD

**Issue by Dolfost** [adi1090x/termux-desktop#79]
Let's say you uploaded a new file to github. How to upgrade Termux Desktop via termux and dont loss your settings on Termux Desktop? (I have a git folder termux-desktop)
![Screenshot_20210801-144815_Termux](https://user-images.githubusercontent.com/59747489/127769763-f8197314-5c66-4be2-a3ff-5e1b2d2cb6ee.png)

**Comment by sayantan300** [comment]
`git pull && ./install.sh`
As said in readme, you can continue installation if there was a network error, so running that install won't be a problem. But yes, the folders that install will change will be made a new backup, so delete the current backup or rename them, and be ready to lose the current folders install had done before. After the installation, you can delete the new folders and replace them with the backup done by install if your files are missing.
