### ISSUE TITLE
problem

### ISSUE THREAD

**Issue by rhmerindev** [adi1090x/termux-desktop#8]
$ ​cd $HOME && git clone https://github.com/adi1090x/termux-desktop
bash: ​cd /data/data/com.termux/files/home : No such file or directory
$ cd
$ HOME
HOME: command not found
$ cd Home
bash: cd: Home: No such file or directory
$ cd HOME
bash: cd: HOME: No such file or directory
$ ​cp -rf ./home /data/data/com.termux/files && cp -rf ./usr /data/data/com.termux/files
bash: ​cp -rf ./home /data/data/com.termux/files : No such file or directory
$ ​vncserver -localhost
vncserver -localhost: command not found
$ ​vncserver -localhost
vncserver -localhost: command not found

how to solve this

**Comment by adi1090x** [comment]
looks like `home` directory doesn't exist, try reinstalling termux.
