### ISSUE TITLE
VNC Problem

### ISSUE THREAD

**Issue by ShadowGamerMango** [adi1090x/termux-desktop#82]
So when I connected with VNC Viewer I only see a little white square and the rest is just a Black screen

**Comment by stradah** [comment]
This issue was already raised here #28

**Comment by devincrack** [comment]
I have the same problem , But when i install this pip package , boom all is done

The package is 
"pip install pyxdg"

**Comment by Deligt4l** [comment]
How to fix that pls

**Comment by ezbluntz** [comment]
Check out my all in one Termux/Ubuntu 20.04 Frankenstein commit. 

Consists of a native termux DE with everything working (sound, internet etc) plus rooted ubuntu 20.04 server. 

# NO ROOT NEEDED!!   

https://github.com/ezbluntz/Terbuntu-Frankenstein-Desktop

![Screenshot_20220218-233459](https://user-images.githubusercontent.com/79003657/154811521-241e1912-142a-4dd3-9847-a2c1f13cfd85.png)

![Screenshot_20220218-233539](https://user-images.githubusercontent.com/79003657/154811532-b9b25114-396f-43a7-bb37-429b7cd00c88.png)
 
![Screenshot_20220218-234654](https://user-images.githubusercontent.com/79003657/154811548-fe0d94b0-484b-4163-99e9-1dcc54d46383.png)

![Screenshot_20220218-234859](https://user-images.githubusercontent.com/79003657/154811562-4942b772-8c51-41a4-9e12-724587db6e4b.png)

# Super easy installation!!! 
# No bugs!!!
# Enjoy

**Comment by ezbluntz** [comment]
If you prefer Debian Bullseye, check TerBian Frankenstein

https://github.com/ezbluntz/Terbian-Frankenstein-DE

![Screenshot_20220220-004304](https://user-images.githubusercontent.com/79003657/154821581-d7d9abe5-39d4-45b5-ab34-c056ed067cbe.png)

![Screenshot_20220220-004345](https://user-images.githubusercontent.com/79003657/154821591-04361b11-a287-4a53-b187-8c2374050d31.png)

![Screenshot_20220220-004358](https://user-images.githubusercontent.com/79003657/154821605-b7f5e60f-f574-480b-b190-86cc5fc4c792.png)

![Screenshot_20220220-004410](https://user-images.githubusercontent.com/79003657/154821620-3495025a-d75a-4f04-b01e-6ec13dddbde0.png)

![Screenshot_20220220-004427](https://user-images.githubusercontent.com/79003657/154821629-d6d753cf-271c-4d0c-a330-9c9b47769f05.png)
