### ISSUE TITLE
Mouse Problem

### ISSUE THREAD

**Issue by JyanJohn** [adi1090x/termux-desktop#84]
I accidentally turned of TigerVNC cursor and now my mouse is not working, is there a way to fix this?

**Comment by PokeyManatee4** [comment]
![bitmoji](https://sdk.bitmoji.com/render/panel/7ff91094-e4e4-496a-9975-c0b5f6ef26ef-11611bb8-08a0-4a48-a006-f38848586588-v1.png?transparent=1&palette=1&width=246) This Is A VNC Viewer Problem So Yeah
