### ISSUE TITLE
Password problem

### ISSUE THREAD

**Issue by tomfowle** [adi1090x/termux-desktop#85]
The installation process did not allow me to enter a password correctly.
I get this far

>[*] Setting up VNC Server...
>
>You will require a password to access your desktops.
>
>Password:

and after I enter a password I get this message

>Verify:Passwords don't match - try again
>Password:

which continues until I press the enter key, whereupon I get the following output
>Password not changed
>sed: can't read /data/data/com.termux/files/home/.vnc/config: No such file or directory

>[*] Script /data/data/com.termux/files/home/.local/bin/startdesktop created successfully.

>[*] Termux Desktop Installed Successfully.

>[-] Restart termux and enter startdesktop command to start the VNC server.
>[-] In VNC client, enter 127.0.0.1:5901 as Address and Password you created to connect.
>[-] To connect via PC over Wifi or Hotspot, use it's IP, ie: 192.168.43.1:5901 to connect. Also, use >TigerVNC client.
>[-] Make sure you enter the correct port. ie: If server is running on Display :2 then port is 5902 and so on.

>   termux-desktop   git:(master)

I have tried the installation process three times, with the same outcome. Is there a way to reset the password? Would that help?

The ./data/data/com.termux/files/home/.vnc/ directory exists but the conf file is missing. Is this missing conf file the source of the problem?

Thanks for your time.
TF

**Comment by rnogy** [comment]
have you tried `vncpasswd` to reset your vnc password? If you want, you can do `rm -rf ~/.vnc` and then start the vncserver to restart the entire vnc setup process.
