### ISSUE TITLE
Nothing happened.

### ISSUE THREAD

**Issue by xpcchx** [adi1090x/termux-desktop#86]
![Screenshot_2021-08-22-08-49-33-780_com termux](https://user-images.githubusercontent.com/64032737/130339281-be1b2a44-142c-4afb-bcb6-60eff74597ed.jpg)
![Screenshot_2021-08-22-08-49-17-923_com realvnc viewer android](https://user-images.githubusercontent.com/64032737/130339283-3b3a9d27-5c48-4614-bdc7-648cbd497d42.jpg)

**Comment by AndyDEV26** [comment]
I have the same problem.

**Comment by Adityapro9** [comment]
I have
