### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by kirillstrelaev4** [adi1090x/termux-desktop#87]
![Screenshot_2021 08 26_16 06 55 733](https://user-images.githubusercontent.com/69953709/130959867-29087459-5eb8-4c6b-a51e-2cdadefad2d6.png)

**Comment by rnogy** [comment]
you sure you're in the right path? You should cd to your termux-desktop directory and then execute the command. If you don't have the folder, you can try cloning the repository again and then `termux-desktop` and `./setup.sh --uninstall`. 

If you really want, just do 
`apt remove bc bmon calc calcurse curl dbus desktop-file-utils elinks feh fontconfig-utils fsmon \
		geany git gtk2 gtk3 htop-legacy imagemagick jq leafpad man mpc mpd mutt ncmpcpp \
		ncurses-utils neofetch netsurf obconf openbox openssl-tool polybar ranger rofi \
		startup-notification termux-api thunar tigervnc vim wget xarchiver xbitmaps xcompmgr \
		xfce4-settings xfce4-terminal xmlstarlet xorg-font-util xorg-xrdb zsh -y --purge --autoremove`
to uninstall the packages

`rm -rf .fehbg .icons .mpd .ncmpcpp .fonts .gtkrc-2.0 .mutt .themes .vnc Music`
to delete all homefiles

`for FILE in hunar geany  gtk-3.0 leafpad netsurf openbox polybar ranger rofi xfce4; do rm -rf $HOME/.config/$FILE; done`
to remove all config files 

`for LOCALFILES in bin lib 'share/backgrounds' 'share/pixmaps'; do rm -rf $HOME/.local/$LOCALFILES; done`
to delete all local files.
