### ISSUE TITLE
mv local dir???

### ISSUE THREAD

**Issue by huazhaozhe** [adi1090x/termux-desktop#88]
Damn it, why do you want the crude mv .local folder? Many things can't be used anymore

**Comment by PokeyManatee4** [comment]
Dats Weird ![bitmoji](https://sdk.bitmoji.com/render/panel/4830816b-79a2-42fb-b8d4-2b0008a78f32-11611bb8-08a0-4a48-a006-f38848586588-v1.png?transparent=1&palette=1&width=246)

**Comment by ZalgoNoise** [comment]
I don't get it. I am not sure if you just don't like it (which is perfectly understandable) or if you're suggesting something. It sounds like the backup actions which I understand, but please confirm what you're referring to specifically.

If you want to file a feature request you can either submit a new PR or be more specific about your goals so we can help you getting it done :)
