### ISSUE TITLE
Music

### ISSUE THREAD

**Issue by moxndam** [adi1090x/termux-desktop#89]
Sir, i unknownly clicked stop on the music menu, then it dissapeared forever,,,how can i hake it back,,, then can one add more apps?

**Comment by Yisus7u7** [comment]
pkg install audacious

**Comment by ezbluntz** [comment]
Check out my all in one Termux/Ubuntu 20.04 Frankenstein commit. 

Consists of a native termux DE with everything working (sound, internet etc) plus rooted ubuntu 20.04 server. 

# NO ROOT NEEDED!!   

https://github.com/ezbluntz/Terbuntu-Frankenstein-Desktop

![Screenshot_20220218-233459](https://user-images.githubusercontent.com/79003657/154811521-241e1912-142a-4dd3-9847-a2c1f13cfd85.png)

![Screenshot_20220218-233539](https://user-images.githubusercontent.com/79003657/154811532-b9b25114-396f-43a7-bb37-429b7cd00c88.png)
 
![Screenshot_20220218-234654](https://user-images.githubusercontent.com/79003657/154811548-fe0d94b0-484b-4163-99e9-1dcc54d46383.png)

![Screenshot_20220218-234859](https://user-images.githubusercontent.com/79003657/154811562-4942b772-8c51-41a4-9e12-724587db6e4b.png)

Super easy installation!!!
