### ISSUE TITLE
Bug running script

### ISSUE THREAD

**Issue by cyroilt** [adi1090x/termux-desktop#92]
![Screenshot_2021-10-05-20-23-26-60_8659c1e795b4b4239e38d87c88c077b3](https://user-images.githubusercontent.com/55390507/136072435-57ea52b7-e02a-48a4-b522-02d730af6721.jpg)

**Comment by ZalgoNoise** [comment]
An `exec /bin/sh` action is a root action, not supported by this repo. Please review your actions to understand where it stems from, since the shells used within Termux are within `/data/data/com.termux/files/usr/bin`

**Comment by ezbluntz** [comment]
Check out my all in one Termux/Ubuntu 20.04 Frankenstein commit. 

Consists of a native termux DE with everything working (sound, internet etc) plus rooted ubuntu 20.04 server. 

# NO ROOT NEEDED!!   

https://github.com/ezbluntz/Terbuntu-Frankenstein-Desktop

![Screenshot_20220218-233459](https://user-images.githubusercontent.com/79003657/154811521-241e1912-142a-4dd3-9847-a2c1f13cfd85.png)

![Screenshot_20220218-233539](https://user-images.githubusercontent.com/79003657/154811532-b9b25114-396f-43a7-bb37-429b7cd00c88.png)
 
![Screenshot_20220218-234654](https://user-images.githubusercontent.com/79003657/154811548-fe0d94b0-484b-4163-99e9-1dcc54d46383.png)

![Screenshot_20220218-234859](https://user-images.githubusercontent.com/79003657/154811562-4942b772-8c51-41a4-9e12-724587db6e4b.png)

Super easy installation!!!
