### ISSUE TITLE
Doesn`t work pls help

### ISSUE THREAD

**Issue by screaze** [adi1090x/termux-desktop#95]
I dont know about that
Termux i closed, all pkg installed
![Screenshot_20211108-001657_Termux](https://user-images.githubusercontent.com/91967355/140662166-5153dd7e-7b30-4234-a38d-81d357f03cc5.jpg)

**Comment by screaze** [comment]
Идите нахуй, месяц почти ждал пидорасы английские

**Comment by KevinBlue18** [comment]
You need to use a separate Android app to view the GUI like [VNC Viewer](https://play.google.com/store/apps/details?id=com.realvnc.viewer.android). You cannot do it directly from Termux.

**Comment by Krish848** [comment]
I m already use vnc viewer
