### ISSUE TITLE
I have a black screen in my VNC VIEWER! 

### ISSUE THREAD

**Issue by m1lsh1n** [adi1090x/termux-desktop#98]
Hello. I using your vnc viewer, but before login to the tigervnc i have black screen. Please, help. (my english may be bad, im from Russia)

**Comment by nithigd5** [comment]
I too have a black screen issue when I use  with VNC Viewer and also getting error when I login with bVNC

**Comment by xXRXDX** [comment]
![Screenshot_2022-01-26-20-06-06-41_8659c1e795b4b4239e38d87c88c077b3](https://user-images.githubusercontent.com/90666354/151160833-2a722ccc-8212-4b4a-b74b-346c144fae03.jpg)
Me too

**Comment by wonder992** [comment]
I also got the same black blank screen on the first display created by the script. I just deleted the running vnc process on display :1 and created a new vnc process. To delete the existing vnc process run `startdesktop` on termux and you'll be prompted. If you still get the same black screen, re-run the setup.sh script then delete the first vnc display created after running the script and create a new one.

**Comment by ezbluntz** [comment]
Try my new "Frankenstein Termux Desktop. very easy installation. 

https://github.com/ezbluntz/Terbuntu-Frankenstein-Desktop.git 

![Screenshot_20220218-233459](https://user-images.githubusercontent.com/79003657/154766407-f0bd3a21-67fc-44ed-a7b1-77e6ff3607d7.png)
![Screenshot_20220218-233539](https://user-images.githubusercontent.com/79003657/154766422-a653efce-0648-4b93-83d0-8008613df077.png)
![Screenshot_20220218-234654](https://user-images.githubusercontent.com/79003657/154766435-ba754289-c355-4176-8099-83aa936ad06f.png)
![Screenshot_20220218-234859](https://user-images.githubusercontent.com/79003657/154766457-d6b15cf8-d752-464b-8662-7183a39779e7.png)

**Comment by ezbluntz** [comment]
Check out my all in one Termux/Ubuntu 20.04 Frankenstein commit. 

Consists of a native termux DE with everything working (sound, internet etc) plus rooted ubuntu 20.04 server. 

# NO ROOT NEEDED!!   

https://github.com/ezbluntz/Terbuntu-Frankenstein-Desktop

![Screenshot_20220218-233459](https://user-images.githubusercontent.com/79003657/154811521-241e1912-142a-4dd3-9847-a2c1f13cfd85.png)

![Screenshot_20220218-233539](https://user-images.githubusercontent.com/79003657/154811532-b9b25114-396f-43a7-bb37-429b7cd00c88.png)
 
![Screenshot_20220218-234654](https://user-images.githubusercontent.com/79003657/154811548-fe0d94b0-484b-4163-99e9-1dcc54d46383.png)

![Screenshot_20220218-234859](https://user-images.githubusercontent.com/79003657/154811562-4942b772-8c51-41a4-9e12-724587db6e4b.png)

Super easy installation!!!

**Comment by Rasquirrel** [comment]
What fixed my problem was reboot my cellphone. And after that, opening termux and running a fresh "startdesktop". And, in the VNC Client, switching the image quality to High.
