### ISSUE TITLE
Why can't I use startdesktop?

### ISSUE THREAD

**Issue by Coolpowersearch** [adi1090x/termux-desktop#99]
![Screenshot_2021-12-21-21-00-23-289_com termux](https://user-images.githubusercontent.com/88696336/146934341-156a1080-e67b-4367-8dee-380449ff8bbe.jpg)
After I input the command, it prompts this. I don't know what's going on.

**Comment by DerGoogler** [comment]
Try to restart the app or clear cache

**Comment by ZalgoNoise** [comment]
Hi,

Either the setup did not complete successfully and the launch script is not present, or the folder containing your launch script is not in your `PATH` environment variable.

__To verify what is causing the issue__

Run the command below:

```
echo "Startup file: $(find ${HOME}/. local/bin -maxdepth 1 -name startdesktop -type f -executable)"
echo "PATH: ${PATH}"
```

This shows you whether the startup file exists, and below your `PATH` variable. The latter is important to consider if you want to launch your CLI commands without referencing them by their full path.

So:

If the first command (for the startup file) fails, then reinstall with the original script.

If the second one does not include `$HOME/.local/bin` then you must include it (command below). This means that you could launch the app with dot-slash notation (also below).

To add the `~/.local/bin` dir to your `PATH` run:

```
echo "export PATH=${PATH}:${HOME}/.local/bin" >> ${PREFIX}/etc/profile
```

This places the referred folder in your path, in a system configuration / preferences file. You just need to restart your terminal session.

To run using dot-slash notation, `cd` into the folder and run the app by prefixing `./` a binary or script's name:

```
cd ~/.local/bin 
./startdesktop
```

**Comment by ZalgoNoise** [comment]
Looking back into the setup process, you can see that the same reference for changing the `PATH` as above, is done on [termux-desktop/setup.sh L102](https://github.com/adi1090x/termux-desktop/blob/cea3871e064a8bd28aca8c691f10075b49879532/setup.sh#L102):

```
	sed -i -e 's|# export PATH=.*|export PATH=$HOME/.local/bin:$PATH|g' $HOME/.zshrc
```

The approach above is relying on the `zsh` and `oh-my-zsh` installation to set this part of the `PATH` variable.

This means that `zsh` / `oh-my-zsh` wasn't installed properly or the configuration file is not being loaded. This should also be why your shell is showing the default prompt `{hostname} %` instead of the `oh-my-zsh` defaults.

Please reinstall via the startup script.

**Comment by ZalgoNoise** [comment]
Added the PR below to avoid issues launching the script, even if `zsh` / `oh-my-zsh` fails to install. The point is that a shell (or shell theme)'s installation should not interfere with the reference in the PATH variable (on where the script should be located and executed).

So, the PATH is being exported as a system-wide config file (`/etc/profile`, as in my first comment) to be available in all shells; and it is done as the startup script is built (more coherent with the action it is doing)

**Comment by ZalgoNoise** [comment]
PR #103: Added the PR above to ensure `chsh` is executed independently (and not coupled with other commands) and so that the installer can exec zsh when it completes. This would ensure that a shell-based configuration (where `PATH` is defined in, for this example, `~/.zshrc`) is reloaded.

**Comment by ezbluntz** [comment]
Check out my all in one Termux/Ubuntu 20.04 Frankenstein commit. 

Consists of a native termux DE with everything working (sound, internet etc) plus rooted ubuntu 20.04 server. 

# NO ROOT NEEDED!!   

https://github.com/ezbluntz/Terbuntu-Frankenstein-Desktop

![Screenshot_20220218-233459](https://user-images.githubusercontent.com/79003657/154811521-241e1912-142a-4dd3-9847-a2c1f13cfd85.png)

![Screenshot_20220218-233539](https://user-images.githubusercontent.com/79003657/154811532-b9b25114-396f-43a7-bb37-429b7cd00c88.png)
 
![Screenshot_20220218-234654](https://user-images.githubusercontent.com/79003657/154811548-fe0d94b0-484b-4163-99e9-1dcc54d46383.png)

![Screenshot_20220218-234859](https://user-images.githubusercontent.com/79003657/154811562-4942b772-8c51-41a4-9e12-724587db6e4b.png)

Super easy installation!!!

**Comment by ezbluntz** [comment]
If you prefer Debian Bullseye, check TerBian Frankenstein

https://github.com/ezbluntz/Terbian-Frankenstein-DE

![Screenshot_20220220-004304](https://user-images.githubusercontent.com/79003657/154821581-d7d9abe5-39d4-45b5-ab34-c056ed067cbe.png)

![Screenshot_20220220-004345](https://user-images.githubusercontent.com/79003657/154821591-04361b11-a287-4a53-b187-8c2374050d31.png)

![Screenshot_20220220-004358](https://user-images.githubusercontent.com/79003657/154821605-b7f5e60f-f574-480b-b190-86cc5fc4c792.png)

![Screenshot_20220220-004410](https://user-images.githubusercontent.com/79003657/154821620-3495025a-d75a-4f04-b01e-6ec13dddbde0.png)

![Screenshot_20220220-004427](https://user-images.githubusercontent.com/79003657/154821629-d6d753cf-271c-4d0c-a330-9c9b47769f05.png)
